default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: snapask_test-1_development

test:
  <<: *default
  database: snapask_test-1_test

production:
  <<: *default
  database: snapask_test-1_production
  username: snapask_test-1
  password: <%= ENV['SNAPASK_DATABASE_PASSWORD'] %>
